#ifndef ZG_H
#define ZG_H

#include "rand64/mersenne64.c"


#define PI 3.14159265
#define f(k,i,j) custos[k][i][j] // objetivo k, vertice i j 
#define EPS 1e-9 // qualquer coisa menor que esse valor, é considerado 0
#define PROFUNDIDADEGRID 5 
#define NUMOBJETIVOS 2
#define NUMEROVERTICES 100
// #define NUMARESTAS 6
#define NUMARESTAS ((NUMEROVERTICES*(NUMEROVERTICES-1))/2)
#define PRECISAO 0.00001
#define MAX_K_BEST 10000000//240000// 200000 - 3000000 // este valor representa somente a k-ésima best árvore encontrada e NAO O TAMANHO DA HEAP

// anti 260000
// conc 10000000 // 6000000
#endif


#define NUMEROVERTICES 5
#define NUMEROVERTICES 7
#define NUMEROVERTICES 10
#define NUMEROVERTICES 12
#define NUMEROVERTICES 15
#define NUMEROVERTICES 17
#define NUMEROVERTICES 20
#define NUMEROVERTICES 22
#define NUMEROVERTICES 25
#define NUMEROVERTICES 27
#define NUMEROVERTICES 30
#define NUMEROVERTICES 33
#define NUMEROVERTICES 35
#define NUMEROVERTICES 38
#define NUMEROVERTICES 40
#define NUMEROVERTICES 42
#define NUMEROVERTICES 45
#define NUMEROVERTICES 48
#define NUMEROVERTICES 50
#define NUMEROVERTICES 7
#define NUMEROVERTICES 7
#define NUMEROVERTICES 7
#define NUMEROVERTICES 22
#define NUMEROVERTICES 22
#define NUMEROVERTICES 22
#define NUMEROVERTICES 22
#define NUMEROVERTICES 22
#define NUMEROVERTICES 22
#define NUMEROVERTICES 22
#define NUMEROVERTICES 22
#define NUMEROVERTICES 22
#define NUMEROVERTICES 22
#define NUMEROVERTICES 22
#define NUMEROVERTICES 22
#define NUMEROVERTICES 22
#define NUMEROVERTICES 22
#define NUMEROVERTICES 15
#define NUMEROVERTICES 15
#define NUMEROVERTICES 15
#define NUMEROVERTICES 15
#define NUMEROVERTICES 15
#define NUMEROVERTICES 15
#define NUMEROVERTICES 22
#define NUMEROVERTICES 22
#define NUMEROVERTICES 15
#define NUMEROVERTICES 33
#define NUMEROVERTICES 22
#define NUMEROVERTICES 22
#define NUMEROVERTICES 22
#define NUMEROVERTICES 22
#define NUMEROVERTICES 22
#define NUMEROVERTICES 12
#define NUMEROVERTICES 12
#define NUMEROVERTICES 12
#define NUMEROVERTICES 12
#define NUMEROVERTICES 12
#define NUMEROVERTICES 12
#define NUMEROVERTICES 12
#define NUMEROVERTICES 4
#define NUMEROVERTICES 4
#define NUMEROVERTICES 4
#define NUMEROVERTICES 4
#define NUMEROVERTICES 4
#define NUMEROVERTICES 4
#define NUMEROVERTICES 22
#define NUMEROVERTICES 15
#define NUMEROVERTICES 15
#define NUMEROVERTICES 15
#define NUMEROVERTICES 15
#define NUMEROVERTICES 15
#define NUMEROVERTICES 15
